dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: halogo-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.259
- name: halogo-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.32
- name: halogo-logistic
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.108
- name: halogo-motorpass
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- name: halogo-payment
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: halogo-price
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: halogo-starcard
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.18
- name: halogo-subscription
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: halogo-vehicle
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.175
