dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: halogo-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.214
- name: halogo-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.30
- name: halogo-logistic
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.78
- name: halogo-motorpass
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: halogo-payment
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: halogo-price
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: halogo-starcard
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: halogo-subscription
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: halogo-vehicle
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.127
