dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: halogo-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.300
- name: halogo-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.32
- name: halogo-logistic
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.124
- name: halogo-price
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: halogo-starcard
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.18
- name: halogo-vehicle
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.191
